language: python
cache: pip
python:
  - '3.6'
fail_fast: true
before_install:
  - pip install pycodestyle
script:
  - pycodestyle .
  - python -c "import ruamel.yaml; ruamel.yaml.load(open('config.yaml', 'r'), Loader=ruamel.yaml.Loader)"
